using System.Runtime.InteropServices;

namespace Epic.OnlineServices.Leaderboards;

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate void OnQueryLeaderboardDefinitionsCompleteCallbackInternal(ref OnQueryLeaderboardDefinitionsCompleteCallbackInfoInternal data);
